name: ATilionDatastructures
version: 0.0.1
description: It adds a super easy interface for database handling
author: TilionDC

main: me.tiliondc.atd.ATilionDatastructures
database: false

commands:
  atd:
    desciption: General atiliondatastructures command
    permission: atd.admin
    usage: Error, do '/atu help'

permissions:
  atd.admin:
    description: Permission for admin stuff
